package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EraRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public EraRequest() {
	}

}