package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Greeting implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public Greeting() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Greeting(java.lang.String name) {
		this.name = name;
	}

}